//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by sedit.rc
//
#define IDB_OPEN                        101
#define IDB_BRIDGE                      102
#define IDB_BUNKER                      103
#define IDB_CONV                        104
#define IDB_COPY                        105
#define IDB_CUT                         106
#define IDB_DROPPER                     107
#define IDB_EDIT                        108
#define IDB_FILL                        110
#define IDB_FLAG                        111
#define IDB_HPEN                        112
#define IDB_MIRROR                      113
#define IDB_NEW                         114
#define IDB_AUTHOR                      115
#define IDB_PASTE                       116
#define IDB_POLE                        117
#define IDB_ROTATE                      118
#define IDB_SAVE                        119
#define IDB_SELECT                      120
#define IDB_SPAWN                       121
#define IDB_SWITCH                      122
#define IDB_WALL                        123
#define IDB_WARP                        124
#define IDC_FILLBUCKET                  125
#define IDC_BUNKERLEFT                  126
#define IDC_BUNKERRIGHT                 127
#define IDC_BUNKERUP                    128
#define IDC_SELECTER                    129
#define IDC_FLAGGER                     130
#define IDC_BRIDGELR                    131
#define IDC_BRIDGEUD                    132
#define IDC_CURSOR9                     133
#define IDC_BUNKERDOWN                  133
#define IDC_PICKER                      134
#define IDD_MAPINFO                     135
#define IDD_CUSTOMIZE                   136
#define IDD_SETTINGS                    137
#define IDD_OVERVIEW                    138
#define IDD_WARPTOOL                    139
#define IDD_ABOUT                       140
#define IDR_FARPLANE                    141
#define IDR_OVERVIEW2                   143
#define IDI_MAIN                        144
#define IDR_ACCELERATOR                 145
#define IDR_MAINMENU                    146
#define IDB_BITMAP1                     147
#define IDB_LINE                        147
#define COMM_NEW                        402
#define COMM_EDIT                       403
#define COMM_OPEN                       404
#define COMM_SHOWGRID                   405
#define COMM_ABOUT                      406
#define COMM_SAVE                       407
#define COMM_SAVEAS                     408
#define COMM_EXIT                       409
#define COMM_SELECT                     410
#define COMM_HELP                       411
#define COMM_UNDO                       412
#define COMM_MIRROR                     413
#define COMM_ROTATE                     414
#define COMM_SELECTALL                  415
#define COMM_REDO                       416
#define COMM_DELETE                     417
#define COMM_FILLSEL                    418
#define COMM_COPY                       419
#define COMM_CUT                        420
#define COMM_PASTE                      421
#define COMM_WALL                       422
#define COMM_FLAG                       423
#define COMM_POLE                       424
#define COMM_FILL                       425
#define COMM_HOLDING_PEN                426
#define COMM_BUNKER                     427
#define COMM_SPAWN                      428
#define COMM_BRIDGE                     429
#define COMM_WARP                       430
#define COMM_SWITCH                     431
#define COMM_PICKER                     432
#define COMM_CONV                       433
#define COMM_LINE                       434
#define COMM_OVERVIEW                   435
#define COMM_INFO                       436
#define COMM_TILEV                      437
#define COMM_TILEH                      438
#define COMM_CASCADE                    439
#define COMM_ENTER                      440
#define COMM_TAB                        441
#define COMM_DEBUG                      600
#define IDC_MAPNAME                     1001
#define IDC_DESC                        1002
#define IDC_BOUNCIES                    1003
#define IDC_MISSLES                     1004
#define IDC_BOMBS                       1005
#define IDC_LDAMAGE                     1006
#define IDC_SDAMAGE                     1007
#define IDC_RECRATE                     1008
#define IDC_MAXPLAY                     1009
#define IDC_DEFHOLD                     1010
#define IDC_POWUPS                      1011
#define IDC_TEAMS                       1012
#define IDC_FRAG                        1013
#define IDC_FLAG                        1014
#define IDC_SWITCH                      1015
#define IDC_SETSET                      1016
#define IDC_CANSET                      1017
#define IDC_LASERD                      1018
#define IDC_SPECIALD                    1019
#define IDC_RECHARGER                   1020
#define IDC_WALL                        1021
#define IDC_CONV                        1022
#define IDC_SWITCH2                     1023
#define IDC_POLE                        1024
#define IDC_BRIDGE                      1025
#define IDC_BUNKER                      1026
#define IDC_SPAWN                       1027
#define IDC_ADD                         1028
#define IDC_EDIT                        1029
#define IDC_REMOVE                      1030
#define IDC_ASSOC                       1031
#define IDC_ARRANGE                     1032
#define IDC_AUTOPAN                     1033
#define IDC_SYSTRAY                     1034
#define IDC_WALLMODE                    1035
#define IDC_RESTORE                     1036
#define IDC_CUSTOMIZE                   1037
#define IDC_MINIVIEW                    1038
#define IDC_ANIMFRAME                   1039
#define IDC_SOURCE                      1040
#define IDC_DESTINATION                 1041
#define IDC_WARPS                       1042
#define IDC_MAPVIEW                     1043
#define IDC_ANIMS                       1044
#define IDC_VERSION                     1045
#define IDC_AUTHOR                      1046
#define IDC_EXPORT                      1047

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
